In [1]:
# print("Hello world")


Hello world


In [ ]:
Basic Array creation

In [3]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4])    #array
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3,4]     # list 
a

[1, 2, 3, 4]

In [8]:
a = [1,2,3,4.5,"Hello"]
a

[1, 2, 3, 4.5, 'Hello']

In [10]:
np.array(a) # all the datatypes are converted to string

array(['1', '2', '3', '4.5', 'Hello'], dtype='<U32')

In [12]:
b = [1,3,5,6.7]            # everthing will be converted to float datatype.
np.array(b)

array([1. , 3. , 5. , 6.7])

In [15]:
# vectors: one dimentional , matrixes: two-dimentional(multiple rows and  multiple coumns.)

In [ ]:
# Note: list does not supports multi-dimentional

In [5]:
l = [ [1,2,3] , [4,5,6] , [7,8,9] ]              # one dimentional;vector
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)                       # numpy array will show in matrix form.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# Note: more than two dimentionals = Tensors

In [8]:
# Array Generation Function:

In [10]:
np.arange(1,11)              # (start,stop,steps)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr = np.arange(1,11,3)
arr

array([ 1,  4,  7, 10])

In [15]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [19]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
arr = np.linspace(1,5,2)        # linear space  #(start,stop,no.of elements)
arr

array([1., 5.])

In [24]:
arr = np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [25]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
# Random Generation Functions:

In [32]:
np.random.rand(5)                         #(no. of elements needed)

array([0.27596156, 0.95065809, 0.38615416, 0.76704559, 0.43182146])

In [30]:
np.random.rand(10)      # single bracket = vector

array([0.4921574 , 0.52471609, 0.74899754, 0.48551139, 0.31742549,
       0.95767176, 0.4609527 , 0.34085694, 0.50750913, 0.33087012])

In [ ]:
# NOTE: Normalization = numbers range(0,1) Standardization = numbers range(-3,3)

In [31]:
# To generate Standardization values:
np.random.randn(10)

array([ 1.06356639,  0.16099472,  0.39722799, -1.51336416, -1.28644868,
        0.99711303, -0.33688967,  0.33441798,  0.19208713, -2.88956396])

In [35]:
np.random.randint(6)                 # only 1 number will be generated from (1 to 6)

3

In [34]:
np.random.randint(10,20,10)

array([17, 16, 18, 12, 18, 15, 15, 16, 13, 16], dtype=int32)

In [ ]:
# -------- Array Attributes: ------------

In [37]:
arr = np.array([ [1,2,3] , [4,5,6] , [7,8,9] ])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
arr.shape

(3, 3)

In [39]:
arr.size

9

In [40]:
arr.dtype

dtype('int64')

In [ ]:
# ----------------- Array Methods --------------

In [41]:
arr.min()

np.int64(1)

In [42]:
arr.min()

np.int64(1)

In [43]:
arr.max()

np.int64(9)

In [44]:
arr.sum()

np.int64(45)

In [48]:
# Numpy also provides sum function to row and column wise sum.
np.sum(arr,axis=0)          # axis = 0 = column wise sum
                            # axis = 1 = column wise sum

array([12, 15, 18])

In [49]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [50]:
arr.mean()

np.float64(5.0)

In [51]:
arr.std()

np.float64(2.581988897471611)

In [54]:
# argmax = index of maximum element.
arr.argmax()

np.int64(8)

In [55]:
arr.argmin()

np.int64(0)

In [ ]:
# ------------- Reshaping and Resizing -----------------------------

In [56]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [57]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])