In [1]:
import numpy as np

In [ ]:
NUMPY INDEXING AND SLICING OF VECTORS:

In [2]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
# Indexing : same as in lists (0 to n)
arr[2]

np.int64(13)

In [7]:
arr[6]

np.int64(17)

In [17]:
# Slicing: same as in lists (start,stop,steps)
arr[3:7]

array([14, 15, 16, 17])

In [11]:
# start = 0 = default , stop = default = end
arr[:5]

array([11, 12, 13, 14, 15])

In [12]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [15]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [16]:
arr[3::2]

array([14, 16, 18, 20])

In [ ]:
NUMPY INDEXING AND SLICING OF MATRIX

In [18]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arr[0]

array([1, 2, 3, 4, 5])

In [30]:
arr[1]               # [first value = row , second value = column]

array([ 6,  7,  8,  9, 10])

In [21]:
arr[2]


array([11, 12, 13, 14, 15])

In [22]:
arr[0,0]

np.int64(1)

In [23]:
arr[0,4]

np.int64(5)

In [29]:
arr[5,4]

np.int64(30)

In [31]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [35]:
slice2 = arr[ 3:6 ,3:5 ]                    # arr[3:,3:]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [43]:
slice3 = arr[3:4,2:3]
slice3

array([[18]])

In [46]:
arr[:,2]                   # to get column : rows all,select column

array([ 3,  8, 13, 18, 23, 28])

In [47]:
arr[ : , 1 ]

array([ 2,  7, 12, 17, 22, 27])

In [ ]:
BOOLEAN INDEXING

In [53]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [54]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [55]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])