In [1]:
# print("Hello world")


Hello world


In [ ]:
Basic Array creation

In [1]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4])    #array
arr

array([1, 2, 3, 4])

In [6]:
a = [1,2,3,4]     # list 
a

[1, 2, 3, 4]

In [8]:
a = [1,2,3,4.5,"Hello"]
a

[1, 2, 3, 4.5, 'Hello']

In [10]:
np.array(a) # all the datatypes are converted to string

array(['1', '2', '3', '4.5', 'Hello'], dtype='<U32')

In [12]:
b = [1,3,5,6.7]            # everthing will be converted to float datatype.
np.array(b)

array([1. , 3. , 5. , 6.7])

In [15]:
# vectors: one dimentional , matrixes: two-dimentional(multiple rows and  multiple coumns.)

In [ ]:
# Note: list does not supports multi-dimentional

In [19]:
l = [[1,2,3],[4,5,6],[7,8,9]]              # one dimentiona;vector
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(l)                       # numpy array will show in matrix form.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
# Note: more than two dimentionals = Tensors